/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UcusDslRuntimeModule extends AbstractUcusDslRuntimeModule {
}
