package crr.testmodel;

/*Generated by MPS */

import java.util.ArrayList;
import java.util.Scanner;

public class TestModel {
  public static final ArrayList<Product> Products = new ArrayList<Product>();
  public static final ArrayList<GeneralUser> GeneralUsers = new ArrayList<GeneralUser>();
  public static final ArrayList<Buyer> Buyers = new ArrayList<Buyer>();

  public static void main(String[] args) {
    seed();
    userMenu();
  }

  public static void userMenu() {
    int selection = -1;
    Scanner input = new Scanner(System.in);

    while (selection != 0) {
      System.out.println("Roles Menu");
      System.out.println("0 - Exit");
      System.out.println("1 - GeneralUser");
      System.out.println("2 - Buyer");

      try {
        selection = Integer.parseInt(input.nextLine());
      } catch (Exception ex) {
        System.out.println("Invalid option!");
        continue;
      }

      switch (selection) {
        case 0:
          break;
        case 1:
          Scanner inputGeneralUser = new Scanner(System.in);
          for (int i = 0; i < GeneralUsers.size(); i++) {
            System.out.println((i + 1) + "-");
            System.out.println(GeneralUsers.get(i).toString());
          }
          try {
            int optSelectedGeneralUser = Integer.parseInt(inputGeneralUser.nextLine());
            GeneralUsers.get(optSelectedGeneralUser - 1).execute();
          } catch (Exception ex) {
            System.out.println("Invalid option!");
            continue;
          }

          break;
        case 2:
          Scanner inputBuyer = new Scanner(System.in);
          for (int i = 0; i < Buyers.size(); i++) {
            System.out.println((i + 1) + "-");
            System.out.println(Buyers.get(i).toString());
          }
          try {
            int optSelectedBuyer = Integer.parseInt(inputBuyer.nextLine());
            Buyers.get(optSelectedBuyer - 1).execute();
          } catch (Exception ex) {
            System.out.println("Invalid option!");
            continue;
          }

          break;
        default:
          System.out.println("Invalid option");
          break;
      }
    }
  }

  public static void seed() {
    Products.add(new Product(1, "Product Name 1", "Product Description 1"));
    Products.add(new Product(2, "Product Name 2", "Product Description 2"));
    Products.add(new Product(3, "Product Name 3", "Product Description 3"));

    Buyers.add(new Buyer(1,"Buyer 1"));
    Buyers.add(new Buyer(2,"Buyer 2"));
    Buyers.add(new Buyer(3,"Buyer 3"));
  }

}
