//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edom.CRR
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "crr";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"CRR";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Edom";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID CRRDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CRRCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID CRRExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CRRCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewCRRExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CRRCommandSetId), 0x0001);
	
		// Package identifier
		public const string CRRPackageId = "e03ca39d-1a01-4136-8599-83502dd51572";
		
		// Editor factory identifier
		public const string CRREditorFactoryId = "7759ae9f-822b-46f1-8d55-e7e8e7cfc95f";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string CRRModelExplorerToolWindowId = "d1c63123-5261-4fae-9b09-f722f45c8410";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Edom.CRR
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string CRRCommandSetId = "238b4435-a135-425e-9570-c0b0bda7c13b";
	}
}