package crr.googlemaps;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class Place {

  public int Id;
  public String Name;
  public String Description;
  public final List<Rate> Rates = new ArrayList<Rate>();

  public Place() {
  }

  public Place(int id, String Name, String Description) {
    Id = id;
    this.Name = Name;
    this.Description = Description;
  }

  public String toString() {
    String res = "";

    res += "Id: " + Id + ";\n";
    res += "Name" + ": " + Name + ";\n";
    res += "Description" + ": " + Description + ";\n";

    res += "\nComments:\n";

    res += "\nRates:\n";
    for (int i = 0; i < Rates.size(); i++) {
      res += Rates.get(i).toString();
      res += "---------\n";
    }

    return res;
  }
}
