


@startuml


	class Place <<Item>> {
					ID : String
					Name : String
			}

	
			Place "1" *-- "*" Comment
	
	class User <<User>> {
					ID : String
			}





	class Comment <<Review>> {
					Content : String
			}
	
	Comment "*" o-- "*" User

	

@enduml