/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUcusDslScopeProvider extends DelegatingScopeProvider {
}
