package ecommerceRating.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myApprovalProcess__BehaviorDescriptor = new ApprovalProcess__BehaviorDescriptor();
  private final BHDescriptor myApprovalStep__BehaviorDescriptor = new ApprovalStep__BehaviorDescriptor();
  private final BHDescriptor myComment__BehaviorDescriptor = new Comment__BehaviorDescriptor();
  private final BHDescriptor myItem__BehaviorDescriptor = new Item__BehaviorDescriptor();
  private final BHDescriptor myModel__BehaviorDescriptor = new Model__BehaviorDescriptor();
  private final BHDescriptor myRate__BehaviorDescriptor = new Rate__BehaviorDescriptor();
  private final BHDescriptor myReview__BehaviorDescriptor = new Review__BehaviorDescriptor();
  private final BHDescriptor myUser__BehaviorDescriptor = new User__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myApprovalProcess__BehaviorDescriptor;
      case 1:
        return myApprovalStep__BehaviorDescriptor;
      case 2:
        return myComment__BehaviorDescriptor;
      case 3:
        return myItem__BehaviorDescriptor;
      case 4:
        return myModel__BehaviorDescriptor;
      case 5:
        return myRate__BehaviorDescriptor;
      case 6:
        return myReview__BehaviorDescriptor;
      case 7:
        return myUser__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db3L), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db5L), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db9L), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbcL), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbfL), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dc0L), MetaIdFactory.conceptId(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dc2L)).seal();
}
