package CommentReviewRate.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAutomaticValidation = createDescriptorForAutomaticValidation();
  /*package*/ final ConceptDescriptor myConceptComment = createDescriptorForComment();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptIValidate = createDescriptorForIValidate();
  /*package*/ final ConceptDescriptor myConceptManualValidation = createDescriptorForManualValidation();
  /*package*/ final ConceptDescriptor myConceptModel = createDescriptorForModel();
  /*package*/ final ConceptDescriptor myConceptRating = createDescriptorForRating();
  /*package*/ final ConceptDescriptor myConceptSubject = createDescriptorForSubject();
  /*package*/ final EnumerationDescriptor myEnumerationFieldTypes = new EnumerationDescriptor_FieldTypes();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAutomaticValidation, myConceptComment, myConceptField, myConceptIValidate, myConceptManualValidation, myConceptModel, myConceptRating, myConceptSubject);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AutomaticValidation:
        return myConceptAutomaticValidation;
      case LanguageConceptSwitch.Comment:
        return myConceptComment;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.IValidate:
        return myConceptIValidate;
      case LanguageConceptSwitch.ManualValidation:
        return myConceptManualValidation;
      case LanguageConceptSwitch.Model:
        return myConceptModel;
      case LanguageConceptSwitch.Rating:
        return myConceptRating;
      case LanguageConceptSwitch.Subject:
        return myConceptSubject;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationFieldTypes);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAutomaticValidation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "AutomaticValidation", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9aded9158cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9aded91589L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1457367043897103756");
    b.version(2);
    b.alias("Automatic Validation Concept");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "Comment", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62c9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1736855509741036233");
    b.version(2);
    b.aggregate("Fields", 0x6166ac460ee473c4L).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62ccL).optional(false).ordered(true).multiple(true).origin("7018486486201037764").done();
    b.aggregate("SubComments", 0x6166ac460e79b4f5L).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62c9L).optional(true).ordered(true).multiple(true).origin("7018486486194042101").done();
    b.aggregate("Ratings", 0x14399b9adedd82eaL).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9adedba652L).optional(true).ordered(true).multiple(true).origin("1457367043897393898").done();
    b.aggregate("AutomaticValidation", 0x14399b9adee1c2b5L).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9aded9158cL).optional(true).ordered(true).multiple(false).origin("1457367043897672373").done();
    b.aggregate("ManualValidation", 0x14399b9adee1c2baL).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9adedba655L).optional(true).ordered(true).multiple(false).origin("1457367043897672378").done();
    b.alias("Comment Concept");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "Field", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62ccL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1736855509741036236");
    b.version(2);
    b.property("Type", 0x181a8ce2444b62ddL).type(MetaIdFactory.dataTypeId(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62cfL)).origin("1736855509741036253").done();
    b.alias("Field ");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIValidate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "IValidate", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9aded91589L);
    b.interface_();
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1457367043897103753");
    b.version(2);
    b.property("validation", 0x14399b9aded9158aL).type(PrimitiveTypeId.BOOLEAN).origin("1457367043897103754").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForManualValidation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "ManualValidation", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9adedba655L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9aded91589L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1457367043897271893");
    b.version(2);
    b.alias("Manual Validation Concept");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "Model", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x6166ac460e810705L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/7018486486194521861");
    b.version(2);
    b.aggregate("Subjects", 0x6166ac460e810826L).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62beL).optional(true).ordered(true).multiple(true).origin("7018486486194522150").done();
    b.alias("Model Concept");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRating() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "Rating", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x14399b9adedba652L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1457367043897271890");
    b.version(2);
    b.aggregate("Fields", 0x14399b9adeddbbd4L).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62ccL).optional(true).ordered(true).multiple(true).origin("1457367043897408468").done();
    b.alias("Rating Concept");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CommentReviewRate", "Subject", 0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62beL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e697bd15-f803-427d-9eeb-a531024193a5(CommentReviewRate.structure)/1736855509741036222");
    b.version(2);
    b.aggregate("Comments", 0x181a8ce2444b62dfL).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62c9L).optional(false).ordered(true).multiple(true).origin("1736855509741036255").done();
    b.aggregate("Fields", 0x181a8ce2444b62ecL).target(0xf07b76fcfe824d2cL, 0x8d3502e79970824dL, 0x181a8ce2444b62ccL).optional(false).ordered(true).multiple(true).origin("1736855509741036268").done();
    b.alias("Subject Concept");
    return b.create();
  }
}
