/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UcusDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pt/isep/edom/i160826/parser/antlr/internal/InternalUcusDsl.tokens");
	}
}
