/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pt.isep.edom.i160826.parser.antlr.internal.InternalUcusDslParser;
import pt.isep.edom.i160826.services.UcusDslGrammarAccess;

public class UcusDslParser extends AbstractAntlrParser {

	@Inject
	private UcusDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUcusDslParser createParser(XtextTokenStream stream) {
		return new InternalUcusDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public UcusDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UcusDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
