package ModelTest.Testing;

/*Generated by MPS */


public class Ator_A {
  public String ator_a;

  public void Ator_A(String name) {
    this.ator_a = name;
  }

  public String getName() {
    return this.ator_a;
  }

  public void setName(String newValue) {
    this.ator_a = newValue;
  }
}
