package ModelTest.Testing;

/*Generated by MPS */


public class SubjectB {
  public String subjectb;

  public void SubjectB(String name) {
    this.subjectb = name;
  }

  public String getName() {
    return this.subjectb;
  }

  public void setName(String newValue) {
    this.subjectb = newValue;
  }

}
