package ModelTest.Testing;

/*Generated by MPS */


public class UCUS {

  public Ator_A ator_a = new Ator_A();
  public Ator_B ator_b = new Ator_B();

  public Association1 association1 = new Association1();

  public SubjectA subjecta = new SubjectA();
  public SubjectB subjectb = new SubjectB();

  public Usecase_AB usecase_ab = new Usecase_AB();



  public void UCUS() {
  }
}
