package ModelTest.Testing;

/*Generated by MPS */


public class Usecase_AB {
  public String usecase_ab;

  public void Usecase_AB(String name) {
    this.usecase_ab = name;
  }

  public String getName() {
    return this.usecase_ab;
  }

  public void setName(String newValue) {
    this.usecase_ab = newValue;
  }

}
