//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDOM.CommentReviewRate
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "crr";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"CommentReviewRate";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"EDOM";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID CommentReviewRateDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CommentReviewRateCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID CommentReviewRateExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CommentReviewRateCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewCommentReviewRateExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CommentReviewRateCommandSetId), 0x0001);
	
		// Package identifier
		public const string CommentReviewRatePackageId = "affbb2e5-2e3d-4bbc-a1c3-2d137ab623e1";
		
		// Editor factory identifier
		public const string CommentReviewRateEditorFactoryId = "7dc988ad-0e9b-4bd2-812f-f34b96c4a8b0";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string CommentReviewRateModelExplorerToolWindowId = "bc7b5a6d-1b51-471e-aa13-cdbe53a5819f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace EDOM.CommentReviewRate
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string CommentReviewRateCommandSetId = "931f4bc1-95f7-4896-90ad-8cdf36410cb8";
	}
}