package Ucus.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Actor = 0;
  public static final int Association = 1;
  public static final int Extend = 2;
  public static final int Include = 3;
  public static final int Model = 4;
  public static final int Subject = 5;
  public static final int UseCase = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL);
    builder.put(0x53db45f88144b6d3L, Actor);
    builder.put(0x53db45f88144b6d9L, Association);
    builder.put(0x672adb1aec820b21L, Extend);
    builder.put(0x672adb1aec820a00L, Include);
    builder.put(0x53db45f88144b6ceL, Model);
    builder.put(0x53db45f88144b6d6L, Subject);
    builder.put(0x53db45f88144b6e5L, UseCase);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
