package Ucus.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActor = createDescriptorForActor();
  /*package*/ final ConceptDescriptor myConceptAssociation = createDescriptorForAssociation();
  /*package*/ final ConceptDescriptor myConceptExtend = createDescriptorForExtend();
  /*package*/ final ConceptDescriptor myConceptInclude = createDescriptorForInclude();
  /*package*/ final ConceptDescriptor myConceptModel = createDescriptorForModel();
  /*package*/ final ConceptDescriptor myConceptSubject = createDescriptorForSubject();
  /*package*/ final ConceptDescriptor myConceptUseCase = createDescriptorForUseCase();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActor, myConceptAssociation, myConceptExtend, myConceptInclude, myConceptModel, myConceptSubject, myConceptUseCase);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actor:
        return myConceptActor;
      case LanguageConceptSwitch.Association:
        return myConceptAssociation;
      case LanguageConceptSwitch.Extend:
        return myConceptExtend;
      case LanguageConceptSwitch.Include:
        return myConceptInclude;
      case LanguageConceptSwitch.Model:
        return myConceptModel;
      case LanguageConceptSwitch.Subject:
        return myConceptSubject;
      case LanguageConceptSwitch.UseCase:
        return myConceptUseCase;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "Actor", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/6042500258670622419");
    b.version(2);
    b.alias("Actor");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAssociation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "Association", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/6042500258670622425");
    b.version(2);
    b.associate("actor", 0x7970448f614beecL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d3L).optional(false).origin("546910591161515756").done();
    b.associate("useCase", 0x7970448f614bf02L).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6e5L).optional(false).origin("546910591161515778").done();
    b.alias("AssociationActorUseCase");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExtend() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "Extend", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x672adb1aec820b21L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/7433995043612003105");
    b.version(2);
    b.associate("useCase", 0x672adb1aec820bbaL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6e5L).optional(true).origin("7433995043612003258").done();
    b.alias("Extend");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInclude() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "Include", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x672adb1aec820a00L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/7433995043612002816");
    b.version(2);
    b.associate("usecase", 0x672adb1aec820a35L).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6e5L).optional(true).origin("7433995043612002869").done();
    b.alias("Include");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "Model", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6ceL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/466379376403106711");
    b.version(2);
    b.aggregate("actors", 0x53db45f88144b6dcL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d3L).optional(true).ordered(true).multiple(true).origin("6042500258670622428").done();
    b.aggregate("subjects", 0x53db45f88144b6deL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d6L).optional(true).ordered(true).multiple(true).origin("6042500258670622430").done();
    b.aggregate("associations", 0x53db45f88144b6e1L).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d9L).optional(true).ordered(true).multiple(true).origin("6042500258670622433").done();
    b.alias("Model");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "Subject", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/6042500258670622422");
    b.version(2);
    b.aggregate("usecases", 0x53db45f88144b6e8L).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6e5L).optional(true).ordered(true).multiple(true).origin("6042500258670622440").done();
    b.alias("Subject");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUseCase() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ucus", "UseCase", 0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6e5L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f194e3a6-83f0-4612-9c97-92374fdaa044(Ucus.structure)/6042500258670622437");
    b.version(2);
    b.property("description", 0x672adb1aec82f611L).type(PrimitiveTypeId.STRING).origin("7433995043612063249").done();
    b.property("includedUsecases", 0x31d095d0b03002a8L).type(PrimitiveTypeId.STRING).origin("3589533626555957928").done();
    b.property("subjectName", 0x31d095d0b03002abL).type(PrimitiveTypeId.STRING).origin("3589533626555957931").done();
    b.aggregate("association", 0x53db45f881457caaL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x53db45f88144b6d9L).optional(false).ordered(true).multiple(true).origin("6042500258670673066").done();
    b.aggregate("includes", 0x672adb1aec820a5aL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x672adb1aec820a00L).optional(true).ordered(true).multiple(true).origin("7433995043612002906").done();
    b.aggregate("extends", 0x672adb1aec820c2fL).target(0xda81cb8675194951L, 0xaf8e5ee2ae47bbdfL, 0x672adb1aec820b21L).optional(true).ordered(true).multiple(false).origin("7433995043612003375").done();
    b.alias("UseCase");
    return b.create();
  }
}
