package ecommerceRating.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import ecommerceRating.behavior.Model__BehaviorDescriptor;
import ecommerceRating.behavior.Item__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import ecommerceRating.behavior.User__BehaviorDescriptor;
import ecommerceRating.behavior.Comment__BehaviorDescriptor;
import ecommerceRating.behavior.Rate__BehaviorDescriptor;
import ecommerceRating.behavior.Review__BehaviorDescriptor;
import ecommerceRating.behavior.ApprovalStep__BehaviorDescriptor;
import ecommerceRating.behavior.ApprovalProcess__BehaviorDescriptor;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1), PROPS.name$MnvL) + "s";
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "s";
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    return (((Integer) _context.getVariable("cv:counter")) + 1) + " - " + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    return ((Integer) _context.getVariable("cv:counter")) + 1;
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return "input" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_5(final PropertyMacroContext _context) {
    return "optSelected" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_6(final PropertyMacroContext _context) {
    return (String) Model__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVqkW.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_3(final PropertyMacroContext _context) {
    return (String) Item__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVpQx.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + ": ";
  }
  public static Object propertyMacro_GetValue_3_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.item$3lN1), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.item$3lN1), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_5(final PropertyMacroContext _context) {
    if ((boolean) User__BehaviorDescriptor.hasComments_id6BnfTZOEJaG.invoke(_context.getNode())) {
      return "3 - Rate ";
    }
    return "2 - Rate ";
  }
  public static Object propertyMacro_GetValue_3_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.item$3lN1), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_7(final PropertyMacroContext _context) {
    if ((boolean) User__BehaviorDescriptor.hasComments_id6BnfTZOEJaG.invoke(_context.getNode())) {
      return 3;
    }
    return 2;
  }
  public static Object propertyMacro_GetValue_3_8(final PropertyMacroContext _context) {
    return (String) User__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVIVk.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL) + ": ";
  }
  public static Object propertyMacro_GetValue_4_2(final PropertyMacroContext _context) {
    return (String) Comment__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVpKh.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1), PROPS.name$MnvL) + "ById";
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_7_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL) + ": ";
  }
  public static Object propertyMacro_GetValue_7_2(final PropertyMacroContext _context) {
    return (String) Rate__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVEHn.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_8_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_8_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_8_2(final PropertyMacroContext _context) {
    return (String) Review__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVGci.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_9_0(final PropertyMacroContext _context) {
    return "execute";
  }
  public static Object propertyMacro_GetValue_9_1(final PropertyMacroContext _context) {
    return "execute";
  }
  public static Object propertyMacro_GetValue_9_2(final PropertyMacroContext _context) {
    return (String) ApprovalStep__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVpAB.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_10_0(final PropertyMacroContext _context) {
    return (String) ApprovalProcess__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVn$7.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_11_0(final PropertyMacroContext _context) {
    return "create" + ApprovalStep__BehaviorDescriptor.getNameWithoutSpacesAndSpecialChars_id6BnfTZQVpAB.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_2_0(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU) != null;
  }
  public static boolean ifMacro_Condition_2_1(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv) != null;
  }
  public static boolean ifMacro_Condition_2_2(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) != null;
  }
  public static boolean ifMacro_Condition_2_3(final IfMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) == null;
  }
  public static boolean ifMacro_Condition_2_4(final IfMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) == null;
  }
  public static boolean ifMacro_Condition_2_5(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv) != null;
  }
  public static boolean ifMacro_Condition_2_6(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU) != null;
  }
  public static boolean ifMacro_Condition_2_7(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) != null;
  }
  public static boolean ifMacro_Condition_2_8(final IfMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) == null;
  }
  public static boolean ifMacro_Condition_2_9(final IfMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) == null;
  }
  public static boolean ifMacro_Condition_2_10(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU) != null;
  }
  public static boolean ifMacro_Condition_3_0(final IfMacroContext _context) {
    return (boolean) User__BehaviorDescriptor.hasComments_id6BnfTZOEJaG.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_3_1(final IfMacroContext _context) {
    return (boolean) User__BehaviorDescriptor.hasRates_id6BnfTZOFhxf.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_3_2(final IfMacroContext _context) {
    return (boolean) User__BehaviorDescriptor.hasComments_id6BnfTZOEJaG.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_3_3(final IfMacroContext _context) {
    return (boolean) User__BehaviorDescriptor.hasRates_id6BnfTZOFhxf.invoke(_context.getNode());
  }
  public static boolean ifMacro_Condition_4_0(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.approvalProcess$6WQZ) != null;
  }
  public static boolean ifMacro_Condition_5_0(final IfMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) != null;
  }
  public static boolean ifMacro_Condition_5_1(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.comment$3sPv) != null;
  }
  public static boolean ifMacro_Condition_5_2(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$3rEq) != null;
  }
  public static boolean ifMacro_Condition_5_3(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$3rEq) != null;
  }
  public static boolean ifMacro_Condition_5_4(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$3rEq) != null;
  }
  public static boolean ifMacro_Condition_5_5(final IfMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) != null;
  }
  public static boolean ifMacro_Condition_5_6(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rate$3zaU) != null;
  }
  public static boolean ifMacro_Condition_7_0(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.approvalProcess$6oyu) != null;
  }
  public static boolean ifMacro_Condition_7_1(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$HOeW) != null;
  }
  public static boolean ifMacro_Condition_7_2(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$HOeW) != null;
  }
  public static boolean ifMacro_Condition_9_0(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr) != null;
  }
  public static boolean ifMacro_Condition_9_1(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr) == null;
  }
  public static boolean ifMacro_Condition_9_2(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.failureStep$fmZT) != null;
  }
  public static boolean ifMacro_Condition_9_3(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.comment$3sPv) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) == ((SNode) SNodeOperations.getParent(_context.getNode()));
  }
  public static boolean ifMacro_Condition_9_4(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr) != null;
  }
  public static boolean ifMacro_Condition_9_5(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr) == null;
  }
  public static boolean ifMacro_Condition_9_6(final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.failureStep$fmZT) != null;
  }
  public static boolean ifMacro_Condition_9_7(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.rate$3zaU) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) == ((SNode) SNodeOperations.getParent(_context.getNode()));
  }
  public static boolean ifMacro_Condition_9_8(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.comment$3sPv) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) == ((SNode) SNodeOperations.getParent(_context.getNode()));
  }
  public static boolean ifMacro_Condition_9_9(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.rate$3zaU) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) == ((SNode) SNodeOperations.getParent(_context.getNode()));
  }
  public static boolean ifMacro_Condition_10_0(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ) == _context.getNode();
  }
  public static boolean ifMacro_Condition_10_1(final IfMacroContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU) != null && SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu) == _context.getNode();
  }
  public static SNode sourceNodeQuery_1_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1);
  }
  public static SNode sourceNodeQuery_1_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1);
  }
  public static SNode sourceNodeQuery_2_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_2_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU);
  }
  public static SNode sourceNodeQuery_2_2(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU);
  }
  public static SNode sourceNodeQuery_2_3(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_2_4(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_2_5(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_2_6(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_3_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_3_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_4_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_5_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_5_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_5_2(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1);
  }
  public static SNode sourceNodeQuery_5_3(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.comment$3sPv), LINKS.approvalProcess$6WQZ);
  }
  public static SNode sourceNodeQuery_5_4(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rate$3zaU);
  }
  public static SNode sourceNodeQuery_5_5(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rate$3zaU);
  }
  public static SNode sourceNodeQuery_5_6(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1);
  }
  public static SNode sourceNodeQuery_5_7(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$3rEq);
  }
  public static SNode sourceNodeQuery_5_8(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.review$3rEq);
  }
  public static SNode sourceNodeQuery_5_9(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.rate$3zaU), LINKS.approvalProcess$6oyu);
  }
  public static SNode sourceNodeQuery_5_10(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_5_11(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_5_12(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1);
  }
  public static SNode sourceNodeQuery_5_13(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.item$3lN1);
  }
  public static SNode sourceNodeQuery_7_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.review$3rEq);
  }
  public static SNode sourceNodeQuery_7_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_8_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.attribute$e8GJ), LINKS.dataType$j4Zb);
  }
  public static SNode sourceNodeQuery_9_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_2(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.failureStep$fmZT), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_3(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.failureStep$fmZT), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_4(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_9_5(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_6(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.successStep$ffXr), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_7(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.failureStep$fmZT), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_8(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.failureStep$fmZT), LINKS.step$6YfC);
  }
  public static SNode sourceNodeQuery_9_9(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.rate$3zaU);
  }
  public static SNode sourceNodeQuery_9_10(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_9_11(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(SNodeOperations.getParent(_context.getNode()))), LINKS.rate$3zaU);
  }
  public static SNode sourceNodeQuery_10_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.start$9On9), LINKS.step$9MXy);
  }
  public static SNode sourceNodeQuery_10_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.start$9On9), LINKS.step$9MXy);
  }
  public static SNode sourceNodeQuery_10_2(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.comment$3sPv);
  }
  public static SNode sourceNodeQuery_10_3(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.start$9On9), LINKS.step$9MXy);
  }
  public static SNode sourceNodeQuery_10_4(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.start$9On9), LINKS.step$9MXy);
  }
  public static SNode sourceNodeQuery_10_5(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(((SNode) SNodeOperations.getParent(_context.getNode())), LINKS.rate$3zaU);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.users$xpwB);
  }
  public static Iterable<SNode> sourceNodesQuery_1_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.users$xpwB);
  }
  public static Iterable<SNode> sourceNodesQuery_1_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.users$xpwB);
  }
  public static Iterable<SNode> sourceNodesQuery_2_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6Jhy);
  }
  public static Iterable<SNode> sourceNodesQuery_2_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6Jhy);
  }
  public static Iterable<SNode> sourceNodesQuery_2_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6Jhy);
  }
  public static Iterable<SNode> sourceNodesQuery_2_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6Jhy);
  }
  public static Iterable<SNode> sourceNodesQuery_3_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$xqaK);
  }
  public static Iterable<SNode> sourceNodesQuery_3_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$xqaK);
  }
  public static Iterable<SNode> sourceNodesQuery_3_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$xqaK);
  }
  public static Iterable<SNode> sourceNodesQuery_3_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$xqaK);
  }
  public static Iterable<SNode> sourceNodesQuery_4_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6QK_);
  }
  public static Iterable<SNode> sourceNodesQuery_4_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6QK_);
  }
  public static Iterable<SNode> sourceNodesQuery_7_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6hw0);
  }
  public static Iterable<SNode> sourceNodesQuery_7_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6hw0);
  }
  public static Iterable<SNode> sourceNodesQuery_8_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6b$g);
  }
  public static Iterable<SNode> sourceNodesQuery_8_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attributes$6b$g);
  }
  public static Iterable<SNode> sourceNodesQuery_11_0(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.approvalProcesses$3$O1)).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, LINKS.steps$9TZx);
      }
    });
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("1120097950890730437", new SNQ(i++));
    snqMethods.put("1120097950890715971", new SNQ(i++));
    snqMethods.put("1120097950888138829", new SNQ(i++));
    snqMethods.put("7626634450215075030", new SNQ(i++));
    snqMethods.put("7626634450222203452", new SNQ(i++));
    snqMethods.put("7626634450215087849", new SNQ(i++));
    snqMethods.put("7626634450218951463", new SNQ(i++));
    snqMethods.put("7626634450217864564", new SNQ(i++));
    snqMethods.put("7626634450227165546", new SNQ(i++));
    snqMethods.put("7626634450216671836", new SNQ(i++));
    snqMethods.put("7626634450216697842", new SNQ(i++));
    snqMethods.put("7626634450218042848", new SNQ(i++));
    snqMethods.put("7626634450213541533", new SNQ(i++));
    snqMethods.put("7626634450213716801", new SNQ(i++));
    snqMethods.put("7626634450213454193", new SNQ(i++));
    snqMethods.put("7626634450255584113", new SNQ(i++));
    snqMethods.put("7626634450214120434", new SNQ(i++));
    snqMethods.put("7626634450214123851", new SNQ(i++));
    snqMethods.put("7626634450214151851", new SNQ(i++));
    snqMethods.put("7626634450219691960", new SNQ(i++));
    snqMethods.put("7626634450219708902", new SNQ(i++));
    snqMethods.put("7626634450255914219", new SNQ(i++));
    snqMethods.put("7626634450215426634", new SNQ(i++));
    snqMethods.put("7626634450215413787", new SNQ(i++));
    snqMethods.put("7626634450213610506", new SNQ(i++));
    snqMethods.put("7626634450213563238", new SNQ(i++));
    snqMethods.put("7626634450215072095", new SNQ(i++));
    snqMethods.put("7626634450222632130", new SNQ(i++));
    snqMethods.put("7626634450220354150", new SNQ(i++));
    snqMethods.put("7626634450241522564", new SNQ(i++));
    snqMethods.put("7626634450252193488", new SNQ(i++));
    snqMethods.put("7626634450241553249", new SNQ(i++));
    snqMethods.put("7626634450252199952", new SNQ(i++));
    snqMethods.put("7626634450236798756", new SNQ(i++));
    snqMethods.put("7626634450244650834", new SNQ(i++));
    snqMethods.put("7626634450252196942", new SNQ(i++));
    snqMethods.put("7626634450244725652", new SNQ(i++));
    snqMethods.put("7626634450252206186", new SNQ(i++));
    snqMethods.put("7626634450236939119", new SNQ(i++));
    snqMethods.put("7626634450236671814", new SNQ(i++));
    snqMethods.put("7626634450236737890", new SNQ(i++));
    snqMethods.put("7626634450237847933", new SNQ(i++));
    snqMethods.put("7626634450251876536", new SNQ(i++));
    snqMethods.put("7626634450230610733", new SNQ(i++));
    snqMethods.put("7626634450237855182", new SNQ(i++));
    snqMethods.put("7626634450241957448", new SNQ(i++));
    snqMethods.put("7626634450239413200", new SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snqMethods.containsKey(id))) {
      return super.getSourceNodeQuery(identity);
    }
    return snqMethods.get(id);
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_1_0(ctx);
        case 1:
          return QueriesGenerated.sourceNodeQuery_1_1(ctx);
        case 2:
          return QueriesGenerated.sourceNodeQuery_2_0(ctx);
        case 3:
          return QueriesGenerated.sourceNodeQuery_2_1(ctx);
        case 4:
          return QueriesGenerated.sourceNodeQuery_2_2(ctx);
        case 5:
          return QueriesGenerated.sourceNodeQuery_2_3(ctx);
        case 6:
          return QueriesGenerated.sourceNodeQuery_2_4(ctx);
        case 7:
          return QueriesGenerated.sourceNodeQuery_2_5(ctx);
        case 8:
          return QueriesGenerated.sourceNodeQuery_2_6(ctx);
        case 9:
          return QueriesGenerated.sourceNodeQuery_3_0(ctx);
        case 10:
          return QueriesGenerated.sourceNodeQuery_3_1(ctx);
        case 11:
          return QueriesGenerated.sourceNodeQuery_4_0(ctx);
        case 12:
          return QueriesGenerated.sourceNodeQuery_5_0(ctx);
        case 13:
          return QueriesGenerated.sourceNodeQuery_5_1(ctx);
        case 14:
          return QueriesGenerated.sourceNodeQuery_5_2(ctx);
        case 15:
          return QueriesGenerated.sourceNodeQuery_5_3(ctx);
        case 16:
          return QueriesGenerated.sourceNodeQuery_5_4(ctx);
        case 17:
          return QueriesGenerated.sourceNodeQuery_5_5(ctx);
        case 18:
          return QueriesGenerated.sourceNodeQuery_5_6(ctx);
        case 19:
          return QueriesGenerated.sourceNodeQuery_5_7(ctx);
        case 20:
          return QueriesGenerated.sourceNodeQuery_5_8(ctx);
        case 21:
          return QueriesGenerated.sourceNodeQuery_5_9(ctx);
        case 22:
          return QueriesGenerated.sourceNodeQuery_5_10(ctx);
        case 23:
          return QueriesGenerated.sourceNodeQuery_5_11(ctx);
        case 24:
          return QueriesGenerated.sourceNodeQuery_5_12(ctx);
        case 25:
          return QueriesGenerated.sourceNodeQuery_5_13(ctx);
        case 26:
          return QueriesGenerated.sourceNodeQuery_7_0(ctx);
        case 27:
          return QueriesGenerated.sourceNodeQuery_7_1(ctx);
        case 28:
          return QueriesGenerated.sourceNodeQuery_8_0(ctx);
        case 29:
          return QueriesGenerated.sourceNodeQuery_9_0(ctx);
        case 30:
          return QueriesGenerated.sourceNodeQuery_9_1(ctx);
        case 31:
          return QueriesGenerated.sourceNodeQuery_9_2(ctx);
        case 32:
          return QueriesGenerated.sourceNodeQuery_9_3(ctx);
        case 33:
          return QueriesGenerated.sourceNodeQuery_9_4(ctx);
        case 34:
          return QueriesGenerated.sourceNodeQuery_9_5(ctx);
        case 35:
          return QueriesGenerated.sourceNodeQuery_9_6(ctx);
        case 36:
          return QueriesGenerated.sourceNodeQuery_9_7(ctx);
        case 37:
          return QueriesGenerated.sourceNodeQuery_9_8(ctx);
        case 38:
          return QueriesGenerated.sourceNodeQuery_9_9(ctx);
        case 39:
          return QueriesGenerated.sourceNodeQuery_9_10(ctx);
        case 40:
          return QueriesGenerated.sourceNodeQuery_9_11(ctx);
        case 41:
          return QueriesGenerated.sourceNodeQuery_10_0(ctx);
        case 42:
          return QueriesGenerated.sourceNodeQuery_10_1(ctx);
        case 43:
          return QueriesGenerated.sourceNodeQuery_10_2(ctx);
        case 44:
          return QueriesGenerated.sourceNodeQuery_10_3(ctx);
        case 45:
          return QueriesGenerated.sourceNodeQuery_10_4(ctx);
        case 46:
          return QueriesGenerated.sourceNodeQuery_10_5(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("1120097950889559781", new SNsQ(i++));
    snsqMethods.put("7626634450211305057", new SNsQ(i++));
    snsqMethods.put("7626634450211338312", new SNsQ(i++));
    snsqMethods.put("1120097950888138084", new SNsQ(i++));
    snsqMethods.put("7626634450217883118", new SNsQ(i++));
    snsqMethods.put("7626634450217861988", new SNsQ(i++));
    snsqMethods.put("1120097950888173276", new SNsQ(i++));
    snsqMethods.put("7626634450216670579", new SNsQ(i++));
    snsqMethods.put("7626634450216719171", new SNsQ(i++));
    snsqMethods.put("7626634450216696897", new SNsQ(i++));
    snsqMethods.put("7626634450216830724", new SNsQ(i++));
    snsqMethods.put("7626634450218041478", new SNsQ(i++));
    snsqMethods.put("7626634450218068928", new SNsQ(i++));
    snsqMethods.put("7626634450222631527", new SNsQ(i++));
    snsqMethods.put("7626634450223286763", new SNsQ(i++));
    snsqMethods.put("7626634450220353319", new SNsQ(i++));
    snsqMethods.put("7626634450220390756", new SNsQ(i++));
    snsqMethods.put("7626634450237722300", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_0(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_1(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_2(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_3(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_0(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_1(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_2(ctx));
        case 10:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_3(ctx));
        case 11:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_0(ctx));
        case 12:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_1(ctx));
        case 13:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_7_0(ctx));
        case 14:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_7_1(ctx));
        case 15:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8_0(ctx));
        case 16:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8_1(ctx));
        case 17:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_11_0(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("1120097950887621103", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Items"));
    pvqMethods.put("1120097950887647940", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Users"));
    pvqMethods.put("7626634450211306418", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "UserRoleMenu"));
    pvqMethods.put("7626634450211340212", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value"), "1"));
    pvqMethods.put("7626634450211951932", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "userSelection"));
    pvqMethods.put("7626634450224355273", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "optSelected"));
    pvqMethods.put("1120097950887130259", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ModelImpl"));
    pvqMethods.put("1120097950888145834", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Attr"));
    pvqMethods.put("7626634450217870272", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "attr"));
    pvqMethods.put("1120097950888174592", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Attr"));
    pvqMethods.put("1120097950887588042", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ItemImpl"));
    pvqMethods.put("7626634450216677792", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Attr"));
    pvqMethods.put("7626634450216703332", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "attr"));
    pvqMethods.put("7626634450216832159", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "AttrName"));
    pvqMethods.put("7626634450212309468", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Item"));
    pvqMethods.put("7626634450212323009", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Item"));
    pvqMethods.put("7626634450212351941", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "rateMenu"));
    pvqMethods.put("7626634450212333746", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Item"));
    pvqMethods.put("7626634450212750581", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value"), "3"));
    pvqMethods.put("1120097950887612357", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "UserImpl"));
    pvqMethods.put("7626634450218050150", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Attr"));
    pvqMethods.put("7626634450218082130", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Attr:"));
    pvqMethods.put("1120097950888350516", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "CommentImpl"));
    pvqMethods.put("7626634450212935648", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getItemById"));
    pvqMethods.put("7626634450222636403", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Attr"));
    pvqMethods.put("7626634450223288001", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Attr"));
    pvqMethods.put("7626634450214092461", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "RateImpl"));
    pvqMethods.put("7626634450220359027", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Attr"));
    pvqMethods.put("7626634450220392263", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Attr"));
    pvqMethods.put("7626634450214857291", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ReviewImpl"));
    pvqMethods.put("7626634450236798863", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "executeComment"));
    pvqMethods.put("7626634450236939226", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "executeRate"));
    pvqMethods.put("7626634450228447639", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ApprovalStepImpl"));
    pvqMethods.put("7626634450229865134", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ApprovalProcessImpl"));
    pvqMethods.put("7626634450237750884", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "createApprovalStep"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_1_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_1_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_2_1(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_2_2(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_2_3(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_3_0(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_3_1(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_3_2(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_3_3(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_3_4(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_3_5(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_3_6(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_3_7(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_3_8(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_4_1(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_4_2(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_5_0(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_7_1(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_7_2(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_8_0(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_8_1(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_8_2(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_9_0(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_9_1(ctx);
        case 32:
          return QueriesGenerated.propertyMacro_GetValue_9_2(ctx);
        case 33:
          return QueriesGenerated.propertyMacro_GetValue_10_0(ctx);
        case 34:
          return QueriesGenerated.propertyMacro_GetValue_11_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("7626634450214453993", new IfMC(i++));
    imcMethods.put("7626634450214549098", new IfMC(i++));
    imcMethods.put("7626634450227760428", new IfMC(i++));
    imcMethods.put("7626634450227816417", new IfMC(i++));
    imcMethods.put("7626634450227819267", new IfMC(i++));
    imcMethods.put("7626634450227631585", new IfMC(i++));
    imcMethods.put("7626634450221998589", new IfMC(i++));
    imcMethods.put("7626634450256936180", new IfMC(i++));
    imcMethods.put("7626634450256943251", new IfMC(i++));
    imcMethods.put("7626634450256945549", new IfMC(i++));
    imcMethods.put("7626634450221978933", new IfMC(i++));
    imcMethods.put("7626634450212097777", new IfMC(i++));
    imcMethods.put("7626634450212111460", new IfMC(i++));
    imcMethods.put("7626634450212744483", new IfMC(i++));
    imcMethods.put("7626634450212748217", new IfMC(i++));
    imcMethods.put("7626634450228436269", new IfMC(i++));
    imcMethods.put("7626634450255565632", new IfMC(i++));
    imcMethods.put("7626634450213804914", new IfMC(i++));
    imcMethods.put("7626634450215156003", new IfMC(i++));
    imcMethods.put("7626634450215134383", new IfMC(i++));
    imcMethods.put("7626634450215178710", new IfMC(i++));
    imcMethods.put("7626634450255914230", new IfMC(i++));
    imcMethods.put("7626634450214503378", new IfMC(i++));
    imcMethods.put("7626634450255972771", new IfMC(i++));
    imcMethods.put("7626634450215094343", new IfMC(i++));
    imcMethods.put("7626634450223304673", new IfMC(i++));
    imcMethods.put("7626634450252833680", new IfMC(i++));
    imcMethods.put("7626634450245781799", new IfMC(i++));
    imcMethods.put("7626634450245809802", new IfMC(i++));
    imcMethods.put("7626634450236798821", new IfMC(i++));
    imcMethods.put("7626634450244775724", new IfMC(i++));
    imcMethods.put("7626634450244778114", new IfMC(i++));
    imcMethods.put("7626634450244975963", new IfMC(i++));
    imcMethods.put("7626634450236939184", new IfMC(i++));
    imcMethods.put("7626634450236728710", new IfMC(i++));
    imcMethods.put("7626634450236737903", new IfMC(i++));
    imcMethods.put("7626634450229903725", new IfMC(i++));
    imcMethods.put("7626634450229886690", new IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(imcMethods.containsKey(id))) {
      return super.getIfMacroCondition(identity);
    }
    return imcMethods.get(id);
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_2_0(ctx);
        case 1:
          return QueriesGenerated.ifMacro_Condition_2_1(ctx);
        case 2:
          return QueriesGenerated.ifMacro_Condition_2_2(ctx);
        case 3:
          return QueriesGenerated.ifMacro_Condition_2_3(ctx);
        case 4:
          return QueriesGenerated.ifMacro_Condition_2_4(ctx);
        case 5:
          return QueriesGenerated.ifMacro_Condition_2_5(ctx);
        case 6:
          return QueriesGenerated.ifMacro_Condition_2_6(ctx);
        case 7:
          return QueriesGenerated.ifMacro_Condition_2_7(ctx);
        case 8:
          return QueriesGenerated.ifMacro_Condition_2_8(ctx);
        case 9:
          return QueriesGenerated.ifMacro_Condition_2_9(ctx);
        case 10:
          return QueriesGenerated.ifMacro_Condition_2_10(ctx);
        case 11:
          return QueriesGenerated.ifMacro_Condition_3_0(ctx);
        case 12:
          return QueriesGenerated.ifMacro_Condition_3_1(ctx);
        case 13:
          return QueriesGenerated.ifMacro_Condition_3_2(ctx);
        case 14:
          return QueriesGenerated.ifMacro_Condition_3_3(ctx);
        case 15:
          return QueriesGenerated.ifMacro_Condition_4_0(ctx);
        case 16:
          return QueriesGenerated.ifMacro_Condition_5_0(ctx);
        case 17:
          return QueriesGenerated.ifMacro_Condition_5_1(ctx);
        case 18:
          return QueriesGenerated.ifMacro_Condition_5_2(ctx);
        case 19:
          return QueriesGenerated.ifMacro_Condition_5_3(ctx);
        case 20:
          return QueriesGenerated.ifMacro_Condition_5_4(ctx);
        case 21:
          return QueriesGenerated.ifMacro_Condition_5_5(ctx);
        case 22:
          return QueriesGenerated.ifMacro_Condition_5_6(ctx);
        case 23:
          return QueriesGenerated.ifMacro_Condition_7_0(ctx);
        case 24:
          return QueriesGenerated.ifMacro_Condition_7_1(ctx);
        case 25:
          return QueriesGenerated.ifMacro_Condition_7_2(ctx);
        case 26:
          return QueriesGenerated.ifMacro_Condition_9_0(ctx);
        case 27:
          return QueriesGenerated.ifMacro_Condition_9_1(ctx);
        case 28:
          return QueriesGenerated.ifMacro_Condition_9_2(ctx);
        case 29:
          return QueriesGenerated.ifMacro_Condition_9_3(ctx);
        case 30:
          return QueriesGenerated.ifMacro_Condition_9_4(ctx);
        case 31:
          return QueriesGenerated.ifMacro_Condition_9_5(ctx);
        case 32:
          return QueriesGenerated.ifMacro_Condition_9_6(ctx);
        case 33:
          return QueriesGenerated.ifMacro_Condition_9_7(ctx);
        case 34:
          return QueriesGenerated.ifMacro_Condition_9_8(ctx);
        case 35:
          return QueriesGenerated.ifMacro_Condition_9_9(ctx);
        case 36:
          return QueriesGenerated.ifMacro_Condition_10_0(ctx);
        case 37:
          return QueriesGenerated.ifMacro_Condition_10_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink item$3lN1 = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL, 0xf8b6326dc453243L, "item");
    /*package*/ static final SReferenceLink attribute$e8GJ = MetaAdapterFactory.getReferenceLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db8L, 0xf8b6326dc4517c8L, "attribute");
    /*package*/ static final SContainmentLink rate$3zaU = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL, 0xf8b6326dc453252L, "rate");
    /*package*/ static final SContainmentLink comment$3sPv = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL, 0xf8b6326dc45324cL, "comment");
    /*package*/ static final SReferenceLink approvalProcess$6WQZ = MetaAdapterFactory.getReferenceLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db9L, 0xf8b6326dc4532aaL, "approvalProcess");
    /*package*/ static final SReferenceLink approvalProcess$6oyu = MetaAdapterFactory.getReferenceLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbfL, 0xf8b6326dc453278L, "approvalProcess");
    /*package*/ static final SContainmentLink review$3rEq = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL, 0xf8b6326dc453247L, "review");
    /*package*/ static final SReferenceLink review$HOeW = MetaAdapterFactory.getReferenceLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbfL, 0x69d73f9ff5f14caaL, "review");
    /*package*/ static final SContainmentLink successStep$ffXr = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db5L, 0x69d73f9ff578e4a5L, "successStep");
    /*package*/ static final SContainmentLink failureStep$fmZT = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db5L, 0x69d73f9ff578e4aeL, "failureStep");
    /*package*/ static final SContainmentLink dataType$j4Zb = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db7L, 0xf8b6326dc52af49L, "dataType");
    /*package*/ static final SReferenceLink step$6YfC = MetaAdapterFactory.getReferenceLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db6L, 0xf8b6326dc4532b0L, "step");
    /*package*/ static final SContainmentLink start$9On9 = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db3L, 0xf8b6326dc4532daL, "start");
    /*package*/ static final SReferenceLink step$9MXy = MetaAdapterFactory.getReferenceLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db4L, 0xf8b6326dc4532d4L, "step");
    /*package*/ static final SContainmentLink users$xpwB = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL, 0xf8b6326dc450dc3L, "users");
    /*package*/ static final SContainmentLink attributes$6Jhy = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbcL, 0xf8b6326dc45329aL, "attributes");
    /*package*/ static final SContainmentLink attributes$xqaK = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dc2L, 0xf8b6326dc450dc5L, "attributes");
    /*package*/ static final SContainmentLink attributes$6QK_ = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db9L, 0xf8b6326dc4532a5L, "attributes");
    /*package*/ static final SContainmentLink attributes$6hw0 = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbfL, 0xf8b6326dc45326fL, "attributes");
    /*package*/ static final SContainmentLink attributes$6b$g = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dc0L, 0xf8b6326dc45326aL, "attributes");
    /*package*/ static final SContainmentLink approvalProcesses$3$O1 = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450dbeL, 0xf8b6326dc453259L, "approvalProcesses");
    /*package*/ static final SContainmentLink steps$9TZx = MetaAdapterFactory.getContainmentLink(0x358cfdcb6f874ce6L, 0x89199392c76fa40bL, 0xf8b6326dc450db3L, 0xf8b6326dc4532ddL, "steps");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
