package ecommerceRating.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeParent;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ApprovalStep_Constraints extends BaseConstraintsDescriptor {
  public ApprovalStep_Constraints() {
    super(CONCEPTS.ApprovalStep$4b);
  }

  @Override
  protected ConstraintFunction<ConstraintContext_CanBeParent, Boolean> calculateCanBeParentConstraint() {
    return new ConstraintFunction<ConstraintContext_CanBeParent, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeParent context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeAParent(context.getNode(), context.getChildNode(), context.getChildConcept(), context.getLink());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeParentBreakingPoint);
        }

        return result;
      }
    };
  }
  private static boolean staticCanBeAParent(SNode node, SNode childNode, SAbstractConcept childConcept, SContainmentLink link) {
    if (ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.nextSteps$$r1v)).count() > 2) {
      return false;
    }
    return true;
  }
  private static final SNodePointer canBeParentBreakingPoint = new SNodePointer("r:6452e7f6-a842-46f2-905d-e4e014315c56(ecommerceRating.constraints)", "6227873571037878136");

  private static final class CONCEPTS {
    /*package*/ static final SConcept ApprovalStep$4b = MetaAdapterFactory.getConcept(0x6435327aad3b4146L, 0x871110b700cc9d08L, 0x566dda0423a6bc6eL, "ecommerceRating.structure.ApprovalStep");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink nextSteps$$r1v = MetaAdapterFactory.getContainmentLink(0x6435327aad3b4146L, 0x871110b700cc9d08L, 0x566dda0423a6bc6eL, 0x566dda0423a773a8L, "nextSteps");
  }
}
