/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import pt.isep.edom.i160826.ucus.Model

@ExtendWith(InjectionExtension)
@InjectWith(UcusDslInjectorProvider)
class UcusDslParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Model Amazon {
				subject{
					Subject Platform {
						usecase {
							UseCase ReviewProduct {
								
							}
						}
					}
				}
				actor {
					Actor User {
						
					}
				}
				association {
					Association association1 {
						actor User usecase "Platform.ReviewProduct" 
					}
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
