/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826.tests

import com.google.inject.Inject
import org.eclipse.emf.common.util.Diagnostic
import org.eclipse.emf.ecore.util.Diagnostician
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import pt.isep.edom.i160826.ucus.Model

@ExtendWith(InjectionExtension)
@InjectWith(UcusDslInjectorProvider) 
class UcusDSLValidationTest {
	@Inject
	ParseHelper<Model> parseHelper
		 
	// Test validations
	@Test
	def void validateModel() {
		val result = parseHelper.parse('''
			Model amazon {
				subject {
					Subject Amazon {
						usecase {
							UseCase reviewProduct {}
						}
					}
				}	
				actor { 
					Actor User {	
					}
				}
			}
		''')
		Assertions.assertNotNull(result)
		var Diagnostic diag=null
		for (Model m: result.eResource.allContents.toIterable.filter(Model)) {
			diag=Diagnostician.INSTANCE.validate(m)	
		}
		Assertions.assertTrue(diag.severity==Diagnostic.ERROR, '''Should result in validation error!''')
	}	
}
