/*
 * generated by Xtext 2.22.0
 */
package pt.isep.edom.i160826.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UcusDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSubjectKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cSubjectAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cSubjectSubjectParserRuleCall_4_2_0 = (RuleCall)cSubjectAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cSubjectAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cSubjectSubjectParserRuleCall_4_3_1_0 = (RuleCall)cSubjectAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cActorKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cActorAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cActorActorParserRuleCall_5_2_0 = (RuleCall)cActorAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cActorAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cActorActorParserRuleCall_5_3_1_0 = (RuleCall)cActorAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAssociationKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAssociationAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cAssociationAssociationParserRuleCall_6_2_0 = (RuleCall)cAssociationAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAssociationAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cAssociationAssociationParserRuleCall_6_3_1_0 = (RuleCall)cAssociationAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Model:
		//	{Model}
		//	'Model'
		//	name=EString
		//	'{' ('subject' '{' subject+=Subject ("," subject+=Subject)* '}')? ('actor' '{' actor+=Actor ("," actor+=Actor)* '}')?
		//	('association' '{' association+=Association ("," association+=Association)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Model} 'Model' name=EString '{' ('subject' '{' subject+=Subject ("," subject+=Subject)* '}')? ('actor' '{' actor+=Actor
		//("," actor+=Actor)* '}')? ('association' '{' association+=Association ("," association+=Association)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }
		
		//'Model'
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('subject' '{' subject+=Subject ("," subject+=Subject)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'subject'
		public Keyword getSubjectKeyword_4_0() { return cSubjectKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//subject+=Subject
		public Assignment getSubjectAssignment_4_2() { return cSubjectAssignment_4_2; }
		
		//Subject
		public RuleCall getSubjectSubjectParserRuleCall_4_2_0() { return cSubjectSubjectParserRuleCall_4_2_0; }
		
		//("," subject+=Subject)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//subject+=Subject
		public Assignment getSubjectAssignment_4_3_1() { return cSubjectAssignment_4_3_1; }
		
		//Subject
		public RuleCall getSubjectSubjectParserRuleCall_4_3_1_0() { return cSubjectSubjectParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('actor' '{' actor+=Actor ("," actor+=Actor)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'actor'
		public Keyword getActorKeyword_5_0() { return cActorKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//actor+=Actor
		public Assignment getActorAssignment_5_2() { return cActorAssignment_5_2; }
		
		//Actor
		public RuleCall getActorActorParserRuleCall_5_2_0() { return cActorActorParserRuleCall_5_2_0; }
		
		//("," actor+=Actor)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//actor+=Actor
		public Assignment getActorAssignment_5_3_1() { return cActorAssignment_5_3_1; }
		
		//Actor
		public RuleCall getActorActorParserRuleCall_5_3_1_0() { return cActorActorParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('association' '{' association+=Association ("," association+=Association)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'association'
		public Keyword getAssociationKeyword_6_0() { return cAssociationKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//association+=Association
		public Assignment getAssociationAssignment_6_2() { return cAssociationAssignment_6_2; }
		
		//Association
		public RuleCall getAssociationAssociationParserRuleCall_6_2_0() { return cAssociationAssociationParserRuleCall_6_2_0; }
		
		//("," association+=Association)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//association+=Association
		public Assignment getAssociationAssignment_6_3_1() { return cAssociationAssignment_6_3_1; }
		
		//Association
		public RuleCall getAssociationAssociationParserRuleCall_6_3_1_0() { return cAssociationAssociationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class SubjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.Subject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSubjectAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSubjectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsecaseKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cUsecaseAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cUsecaseUseCaseParserRuleCall_4_2_0 = (RuleCall)cUsecaseAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cUsecaseAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cUsecaseUseCaseParserRuleCall_4_3_1_0 = (RuleCall)cUsecaseAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Subject:
		//	{Subject}
		//	'Subject'
		//	name=EString
		//	'{' ('usecase' '{' usecase+=UseCase ("," usecase+=UseCase)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Subject} 'Subject' name=EString '{' ('usecase' '{' usecase+=UseCase ("," usecase+=UseCase)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Subject}
		public Action getSubjectAction_0() { return cSubjectAction_0; }
		
		//'Subject'
		public Keyword getSubjectKeyword_1() { return cSubjectKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('usecase' '{' usecase+=UseCase ("," usecase+=UseCase)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'usecase'
		public Keyword getUsecaseKeyword_4_0() { return cUsecaseKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//usecase+=UseCase
		public Assignment getUsecaseAssignment_4_2() { return cUsecaseAssignment_4_2; }
		
		//UseCase
		public RuleCall getUsecaseUseCaseParserRuleCall_4_2_0() { return cUsecaseUseCaseParserRuleCall_4_2_0; }
		
		//("," usecase+=UseCase)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//usecase+=UseCase
		public Assignment getUsecaseAssignment_4_3_1() { return cUsecaseAssignment_4_3_1; }
		
		//UseCase
		public RuleCall getUsecaseUseCaseParserRuleCall_4_3_1_0() { return cUsecaseUseCaseParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ActorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.Actor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAssociationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAssociationAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cAssociationAssociationCrossReference_4_2_0 = (CrossReference)cAssociationAssignment_4_2.eContents().get(0);
		private final RuleCall cAssociationAssociationEStringParserRuleCall_4_2_0_1 = (RuleCall)cAssociationAssociationCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAssociationAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cAssociationAssociationCrossReference_4_3_1_0 = (CrossReference)cAssociationAssignment_4_3_1.eContents().get(0);
		private final RuleCall cAssociationAssociationEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cAssociationAssociationCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Actor:
		//	{Actor}
		//	'Actor'
		//	name=EString
		//	'{' ('association' '(' association+=[Association|EString] ("," association+=[Association|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Actor} 'Actor' name=EString '{' ('association' '(' association+=[Association|EString] (","
		//association+=[Association|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Actor}
		public Action getActorAction_0() { return cActorAction_0; }
		
		//'Actor'
		public Keyword getActorKeyword_1() { return cActorKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('association' '(' association+=[Association|EString] ("," association+=[Association|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'association'
		public Keyword getAssociationKeyword_4_0() { return cAssociationKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//association+=[Association|EString]
		public Assignment getAssociationAssignment_4_2() { return cAssociationAssignment_4_2; }
		
		//[Association|EString]
		public CrossReference getAssociationAssociationCrossReference_4_2_0() { return cAssociationAssociationCrossReference_4_2_0; }
		
		//EString
		public RuleCall getAssociationAssociationEStringParserRuleCall_4_2_0_1() { return cAssociationAssociationEStringParserRuleCall_4_2_0_1; }
		
		//("," association+=[Association|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//association+=[Association|EString]
		public Assignment getAssociationAssignment_4_3_1() { return cAssociationAssignment_4_3_1; }
		
		//[Association|EString]
		public CrossReference getAssociationAssociationCrossReference_4_3_1_0() { return cAssociationAssociationCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getAssociationAssociationEStringParserRuleCall_4_3_1_0_1() { return cAssociationAssociationEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class AssociationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.Association");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssociationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cActorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cActorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cActorActorCrossReference_4_0 = (CrossReference)cActorAssignment_4.eContents().get(0);
		private final RuleCall cActorActorEStringParserRuleCall_4_0_1 = (RuleCall)cActorActorCrossReference_4_0.eContents().get(1);
		private final Keyword cUsecaseKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUsecaseAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cUsecaseUseCaseCrossReference_6_0 = (CrossReference)cUsecaseAssignment_6.eContents().get(0);
		private final RuleCall cUsecaseUseCaseEStringParserRuleCall_6_0_1 = (RuleCall)cUsecaseUseCaseCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Association:
		//	'Association'
		//	name=EString
		//	'{'
		//	'actor' actor=[Actor|EString]
		//	'usecase' usecase=[UseCase|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Association' name=EString '{' 'actor' actor=[Actor|EString] 'usecase' usecase=[UseCase|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Association'
		public Keyword getAssociationKeyword_0() { return cAssociationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'actor'
		public Keyword getActorKeyword_3() { return cActorKeyword_3; }
		
		//actor=[Actor|EString]
		public Assignment getActorAssignment_4() { return cActorAssignment_4; }
		
		//[Actor|EString]
		public CrossReference getActorActorCrossReference_4_0() { return cActorActorCrossReference_4_0; }
		
		//EString
		public RuleCall getActorActorEStringParserRuleCall_4_0_1() { return cActorActorEStringParserRuleCall_4_0_1; }
		
		//'usecase'
		public Keyword getUsecaseKeyword_5() { return cUsecaseKeyword_5; }
		
		//usecase=[UseCase|EString]
		public Assignment getUsecaseAssignment_6() { return cUsecaseAssignment_6; }
		
		//[UseCase|EString]
		public CrossReference getUsecaseUseCaseCrossReference_6_0() { return cUsecaseUseCaseCrossReference_6_0; }
		
		//EString
		public RuleCall getUsecaseUseCaseEStringParserRuleCall_6_0_1() { return cUsecaseUseCaseEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class UseCaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.UseCase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUseCaseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUseCaseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncludeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncludeAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncludeIncludeCrossReference_4_2_0 = (CrossReference)cIncludeAssignment_4_2.eContents().get(0);
		private final RuleCall cIncludeIncludeEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncludeIncludeCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncludeAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncludeIncludeCrossReference_4_3_1_0 = (CrossReference)cIncludeAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncludeIncludeEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncludeIncludeCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cExtendKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cExtendAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cExtendExtendCrossReference_5_2_0 = (CrossReference)cExtendAssignment_5_2.eContents().get(0);
		private final RuleCall cExtendExtendEStringParserRuleCall_5_2_0_1 = (RuleCall)cExtendExtendCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cExtendAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cExtendExtendCrossReference_5_3_1_0 = (CrossReference)cExtendAssignment_5_3_1.eContents().get(0);
		private final RuleCall cExtendExtendEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cExtendExtendCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAssociationKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAssociationAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cAssociationAssociationCrossReference_6_2_0 = (CrossReference)cAssociationAssignment_6_2.eContents().get(0);
		private final RuleCall cAssociationAssociationEStringParserRuleCall_6_2_0_1 = (RuleCall)cAssociationAssociationCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAssociationAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cAssociationAssociationCrossReference_6_3_1_0 = (CrossReference)cAssociationAssignment_6_3_1.eContents().get(0);
		private final RuleCall cAssociationAssociationEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cAssociationAssociationCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIncludesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cIncludesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cIncludesIncludeParserRuleCall_7_2_0 = (RuleCall)cIncludesAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cIncludesAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cIncludesIncludeParserRuleCall_7_3_1_0 = (RuleCall)cIncludesAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cExtendsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cExtendsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cExtendsExtendParserRuleCall_8_2_0 = (RuleCall)cExtendsAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cExtendsAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cExtendsExtendParserRuleCall_8_3_1_0 = (RuleCall)cExtendsAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//UseCase:
		//	{UseCase}
		//	'UseCase'
		//	name=EString
		//	'{' ('include' '(' include+=[Include|EString] ("," include+=[Include|EString])* ')')? ('extend' '('
		//	extend+=[Extend|EString] ("," extend+=[Extend|EString])* ')')? ('association' '(' association+=[Association|EString]
		//	("," association+=[Association|EString])* ')')? ('includes' '{' includes+=Include ("," includes+=Include)* '}')?
		//	('extends' '{' extends+=Extend ("," extends+=Extend)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{UseCase} 'UseCase' name=EString '{' ('include' '(' include+=[Include|EString] ("," include+=[Include|EString])* ')')?
		//('extend' '(' extend+=[Extend|EString] ("," extend+=[Extend|EString])* ')')? ('association' '('
		//association+=[Association|EString] ("," association+=[Association|EString])* ')')? ('includes' '{' includes+=Include
		//("," includes+=Include)* '}')? ('extends' '{' extends+=Extend ("," extends+=Extend)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{UseCase}
		public Action getUseCaseAction_0() { return cUseCaseAction_0; }
		
		//'UseCase'
		public Keyword getUseCaseKeyword_1() { return cUseCaseKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('include' '(' include+=[Include|EString] ("," include+=[Include|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'include'
		public Keyword getIncludeKeyword_4_0() { return cIncludeKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//include+=[Include|EString]
		public Assignment getIncludeAssignment_4_2() { return cIncludeAssignment_4_2; }
		
		//[Include|EString]
		public CrossReference getIncludeIncludeCrossReference_4_2_0() { return cIncludeIncludeCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncludeIncludeEStringParserRuleCall_4_2_0_1() { return cIncludeIncludeEStringParserRuleCall_4_2_0_1; }
		
		//("," include+=[Include|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//include+=[Include|EString]
		public Assignment getIncludeAssignment_4_3_1() { return cIncludeAssignment_4_3_1; }
		
		//[Include|EString]
		public CrossReference getIncludeIncludeCrossReference_4_3_1_0() { return cIncludeIncludeCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncludeIncludeEStringParserRuleCall_4_3_1_0_1() { return cIncludeIncludeEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('extend' '(' extend+=[Extend|EString] ("," extend+=[Extend|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'extend'
		public Keyword getExtendKeyword_5_0() { return cExtendKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//extend+=[Extend|EString]
		public Assignment getExtendAssignment_5_2() { return cExtendAssignment_5_2; }
		
		//[Extend|EString]
		public CrossReference getExtendExtendCrossReference_5_2_0() { return cExtendExtendCrossReference_5_2_0; }
		
		//EString
		public RuleCall getExtendExtendEStringParserRuleCall_5_2_0_1() { return cExtendExtendEStringParserRuleCall_5_2_0_1; }
		
		//("," extend+=[Extend|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//extend+=[Extend|EString]
		public Assignment getExtendAssignment_5_3_1() { return cExtendAssignment_5_3_1; }
		
		//[Extend|EString]
		public CrossReference getExtendExtendCrossReference_5_3_1_0() { return cExtendExtendCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getExtendExtendEStringParserRuleCall_5_3_1_0_1() { return cExtendExtendEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('association' '(' association+=[Association|EString] ("," association+=[Association|EString])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'association'
		public Keyword getAssociationKeyword_6_0() { return cAssociationKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//association+=[Association|EString]
		public Assignment getAssociationAssignment_6_2() { return cAssociationAssignment_6_2; }
		
		//[Association|EString]
		public CrossReference getAssociationAssociationCrossReference_6_2_0() { return cAssociationAssociationCrossReference_6_2_0; }
		
		//EString
		public RuleCall getAssociationAssociationEStringParserRuleCall_6_2_0_1() { return cAssociationAssociationEStringParserRuleCall_6_2_0_1; }
		
		//("," association+=[Association|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//association+=[Association|EString]
		public Assignment getAssociationAssignment_6_3_1() { return cAssociationAssignment_6_3_1; }
		
		//[Association|EString]
		public CrossReference getAssociationAssociationCrossReference_6_3_1_0() { return cAssociationAssociationCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getAssociationAssociationEStringParserRuleCall_6_3_1_0_1() { return cAssociationAssociationEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('includes' '{' includes+=Include ("," includes+=Include)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'includes'
		public Keyword getIncludesKeyword_7_0() { return cIncludesKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//includes+=Include
		public Assignment getIncludesAssignment_7_2() { return cIncludesAssignment_7_2; }
		
		//Include
		public RuleCall getIncludesIncludeParserRuleCall_7_2_0() { return cIncludesIncludeParserRuleCall_7_2_0; }
		
		//("," includes+=Include)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//includes+=Include
		public Assignment getIncludesAssignment_7_3_1() { return cIncludesAssignment_7_3_1; }
		
		//Include
		public RuleCall getIncludesIncludeParserRuleCall_7_3_1_0() { return cIncludesIncludeParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('extends' '{' extends+=Extend ("," extends+=Extend)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'extends'
		public Keyword getExtendsKeyword_8_0() { return cExtendsKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//extends+=Extend
		public Assignment getExtendsAssignment_8_2() { return cExtendsAssignment_8_2; }
		
		//Extend
		public RuleCall getExtendsExtendParserRuleCall_8_2_0() { return cExtendsExtendParserRuleCall_8_2_0; }
		
		//("," extends+=Extend)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//extends+=Extend
		public Assignment getExtendsAssignment_8_3_1() { return cExtendsAssignment_8_3_1; }
		
		//Extend
		public RuleCall getExtendsExtendParserRuleCall_8_3_1_0() { return cExtendsExtendParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class IncludeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.Include");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIncludeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAdditionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAdditionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cAdditionUseCaseCrossReference_4_0 = (CrossReference)cAdditionAssignment_4.eContents().get(0);
		private final RuleCall cAdditionUseCaseEStringParserRuleCall_4_0_1 = (RuleCall)cAdditionUseCaseCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Include:
		//	'Include'
		//	name=EString
		//	'{'
		//	'addition' addition=[UseCase|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Include' name=EString '{' 'addition' addition=[UseCase|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Include'
		public Keyword getIncludeKeyword_0() { return cIncludeKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'addition'
		public Keyword getAdditionKeyword_3() { return cAdditionKeyword_3; }
		
		//addition=[UseCase|EString]
		public Assignment getAdditionAssignment_4() { return cAdditionAssignment_4; }
		
		//[UseCase|EString]
		public CrossReference getAdditionUseCaseCrossReference_4_0() { return cAdditionUseCaseCrossReference_4_0; }
		
		//EString
		public RuleCall getAdditionUseCaseEStringParserRuleCall_4_0_1() { return cAdditionUseCaseEStringParserRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ExtendElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.i160826.UcusDsl.Extend");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExtendKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cExtendedCaseKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExtendedCaseAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cExtendedCaseUseCaseCrossReference_4_0 = (CrossReference)cExtendedCaseAssignment_4.eContents().get(0);
		private final RuleCall cExtendedCaseUseCaseEStringParserRuleCall_4_0_1 = (RuleCall)cExtendedCaseUseCaseCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Extend:
		//	'Extend'
		//	name=EString
		//	'{'
		//	'extendedCase' extendedCase=[UseCase|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Extend' name=EString '{' 'extendedCase' extendedCase=[UseCase|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Extend'
		public Keyword getExtendKeyword_0() { return cExtendKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'extendedCase'
		public Keyword getExtendedCaseKeyword_3() { return cExtendedCaseKeyword_3; }
		
		//extendedCase=[UseCase|EString]
		public Assignment getExtendedCaseAssignment_4() { return cExtendedCaseAssignment_4; }
		
		//[UseCase|EString]
		public CrossReference getExtendedCaseUseCaseCrossReference_4_0() { return cExtendedCaseUseCaseCrossReference_4_0; }
		
		//EString
		public RuleCall getExtendedCaseUseCaseEStringParserRuleCall_4_0_1() { return cExtendedCaseUseCaseEStringParserRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final ModelElements pModel;
	private final SubjectElements pSubject;
	private final ActorElements pActor;
	private final EStringElements pEString;
	private final AssociationElements pAssociation;
	private final UseCaseElements pUseCase;
	private final IncludeElements pInclude;
	private final ExtendElements pExtend;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UcusDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pSubject = new SubjectElements();
		this.pActor = new ActorElements();
		this.pEString = new EStringElements();
		this.pAssociation = new AssociationElements();
		this.pUseCase = new UseCaseElements();
		this.pInclude = new IncludeElements();
		this.pExtend = new ExtendElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("pt.isep.edom.i160826.UcusDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model}
	//	'Model'
	//	name=EString
	//	'{' ('subject' '{' subject+=Subject ("," subject+=Subject)* '}')? ('actor' '{' actor+=Actor ("," actor+=Actor)* '}')?
	//	('association' '{' association+=Association ("," association+=Association)* '}')?
	//	'}';
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Subject:
	//	{Subject}
	//	'Subject'
	//	name=EString
	//	'{' ('usecase' '{' usecase+=UseCase ("," usecase+=UseCase)* '}')?
	//	'}';
	public SubjectElements getSubjectAccess() {
		return pSubject;
	}
	
	public ParserRule getSubjectRule() {
		return getSubjectAccess().getRule();
	}
	
	//Actor:
	//	{Actor}
	//	'Actor'
	//	name=EString
	//	'{' ('association' '(' association+=[Association|EString] ("," association+=[Association|EString])* ')')?
	//	'}';
	public ActorElements getActorAccess() {
		return pActor;
	}
	
	public ParserRule getActorRule() {
		return getActorAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Association:
	//	'Association'
	//	name=EString
	//	'{'
	//	'actor' actor=[Actor|EString]
	//	'usecase' usecase=[UseCase|EString]
	//	'}';
	public AssociationElements getAssociationAccess() {
		return pAssociation;
	}
	
	public ParserRule getAssociationRule() {
		return getAssociationAccess().getRule();
	}
	
	//UseCase:
	//	{UseCase}
	//	'UseCase'
	//	name=EString
	//	'{' ('include' '(' include+=[Include|EString] ("," include+=[Include|EString])* ')')? ('extend' '('
	//	extend+=[Extend|EString] ("," extend+=[Extend|EString])* ')')? ('association' '(' association+=[Association|EString]
	//	("," association+=[Association|EString])* ')')? ('includes' '{' includes+=Include ("," includes+=Include)* '}')?
	//	('extends' '{' extends+=Extend ("," extends+=Extend)* '}')?
	//	'}';
	public UseCaseElements getUseCaseAccess() {
		return pUseCase;
	}
	
	public ParserRule getUseCaseRule() {
		return getUseCaseAccess().getRule();
	}
	
	//Include:
	//	'Include'
	//	name=EString
	//	'{'
	//	'addition' addition=[UseCase|EString]
	//	'}';
	public IncludeElements getIncludeAccess() {
		return pInclude;
	}
	
	public ParserRule getIncludeRule() {
		return getIncludeAccess().getRule();
	}
	
	//Extend:
	//	'Extend'
	//	name=EString
	//	'{'
	//	'extendedCase' extendedCase=[UseCase|EString]
	//	'}';
	public ExtendElements getExtendAccess() {
		return pExtend;
	}
	
	public ParserRule getExtendRule() {
		return getExtendAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
